server:
  port : 8081

parcom:
  services:
    classroom:
      host: pc-classroom
      port: 8080

spring:
  application.name: pc-security
  hateoas:
    use-hal-as-default-json-media-type: false
  datasource:
    url: jdbc:postgresql://pc-security-pg:5433/postgres
    username: postgres
    password: parcom
    platform: postgres
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    database: postgresql
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
         jdbc:
          lob:
            non_contextual_creation: true
  data:
    rest:
      detection-strategy: annotated
